<?php
//Adds the custom fields for the post/page areas

/* ============================================================================
All the hooks for adding and saving boxes/data
==============================================================================*/
add_action('admin_init','add_boxes'); // Required to add new meta boxes
add_action('save_post', 'dws_save_data'); // Requires to SAVE the information in said meta boxes

/* ============================================================================
Adds the meta boxes to their respective locations
==============================================================================*/

function add_boxes (){
  add_meta_box("ad_secondary", "Secondary Content", "ad_wp_editor",   "page", "normal", "high");
}
 
  
/* ============================================================================
Generates a textarea using the Wordpress editor area in a separate meta box
==============================================================================*/

function ad_wp_editor($post ) { 
  if($post->page_template != 'page-two-column.php'){
    
    echo('<p>This page template isn\'t setup to handle secondary content. Switch to the <strong>"Two Editable Columns"</strong> template to activate this area.</p>');
    
  }else{
  
    
   	$value = get_post_meta($post->ID,'_ad_secondary_content',true); ?>
      <!-- Nonce stands for Number Once-->
    <input type="hidden" name="dws_noncename" id="dws_noncename" value="<?php echo(wp_create_nonce('dws_nonce')); ?>" />
      <?php wp_editor( $value, 'ad_secondary_content');  
      
  }    
 }
 
 
 
 

/* ============================================================================
Saves the data generated by the meta boxes
==============================================================================*/

function dws_save_data($post_id) { 
    global $post;
      if (!wp_verify_nonce($_POST['dws_noncename'], 'dws_nonce')) return $post_id;  // verify this with nonce because save_post can be triggered at other times     
     if (defined('DOING_AUTOSAVE') && DOING_AUTOSAVE) return $post_id; // do not save if this is an auto save routine
	
  $ad_secondary_content = $_POST['ad_secondary_content'];
   update_post_meta($post_id, '_ad_secondary_content', $ad_secondary_content); 
 } 
 
function dws_save_dynamic_data($post_id) { 

} 
 ?>